# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.

# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.
title: "Personal Website"
google_analytics: "UA-102245386-2"
email: "charlesmulder@protonmail.com"
description: >- # this means to ignore newlines until "baseurl:"
  Hello world. I am Charles Mulder. Welcome to my personal website about music, movement and computer programming.
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://charlesmulder.net" # the base hostname & protocol for your site, e.g. http://example.com
twitter_username: jekyllrb
github_username:  jekyll

# Build settings
markdown: kramdown
theme: monomulder
plugins:
  - jekyll-feed
sass:
  style: compact

collections: 
  music:
    output: true
  movement: 
    output: true
  programming:
    output: true

kramdown:
  parse_block_html: true

permalink: /:categories/:title/
